import type { Metadata } from 'next'
import './globals.css'
import { notFound } from 'next/navigation'
import ClientSideProvider from './ClientSideProvider'
import { locales } from '@/language'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export function generateStaticParams() {
  return locales.map(locale => ({ locale }))
}

export default async function RootLayout({
  children,
  modal,
  params: { locale }
}: {
  children: React.ReactNode,
  modal: React.ReactNode,
  params: { locale: string }
}) {

  let messages = [];
  try {
    messages = (await import(`messages/${locale}.json`)).default;
  } catch (error) {
    console.log('message error', error);

    notFound()
  }

  return (
    <html lang="en">
      <body>
        <ClientSideProvider
          messages={messages}
          locale={locale}
        >
          {children}
          {modal}
        </ClientSideProvider>

      </body>
    </html>
  )
}
